networks:
  internal:
    driver: bridge

volumes:
  mysql-data:
    driver: local

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: belpao
      MYSQL_USER: belpao
      MYSQL_PASSWORD: belpao
    volumes:
      #- ./bd:/docker-entrypoint-initdb.d  # Caminho correto para o SQL
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306/tcp
    networks:
      - internal
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      timeout: 10s
      retries: 5
